SET mapreduce.map.memory.mb = 3584;
SET mapreduce.reduce.memory.mb = 3584;
SET mapreduce.map.java.opts = -Xmx2867m;
SET mapreduce.reduce.java.opts = -Xmx2867m;
SET mapreduce.map.cpu.vcores = 2;
SET mapreduce.reduce.cpu.vcores = 2;

DROP TABLE IF EXISTS saket.tableau_geo_report_tmp;
CREATE TABLE saket.tableau_geo_report_tmp
AS
SELECT
  a.UTC_dt,
  a.geo_country,
  a.de_country_name,
  a.advertiser_id,
  a.advertiser,
  a.category,
  a.subcategory,
  a.agency,
  a.insertion_order_id,
  a.insertion_order,
  a.campaign_group_id,
  a.lineitem,
  a.campaign_id,
  a.campaign,
  a.pixel_id,
  a.pixel,
  a.dayserial_numeric,
  a.geo_region,
  a.geo_region_name,
  a.city_id,
  a.city_name,
  a.city_region,
  a.GEO_DMA,
  a.POSTAL_CODE,
  a.lat,
  a.lon,
  a.imp,
  a.click,
  a.pc_conv,
  a.pv_conv,
  CAST(a.media_cost_dollars_cpm as DOUBLE) AS media_cost_dollars_cpm,
  CAST(a.buyer_spend as DOUBLE) AS buyer_spend,
  b.miq_advertiser_id,
  b.miq_advertiser_name,
  b.agency_id,
  b.agency_name,
  b.campaign_id AS jarvis_campaign_id,
  b.dsp
FROM saket.tableau_geo_report a
LEFT JOIN saket.combined_dsp_lookup b ON a.insertion_order_id = b.insertion_order_id and a.campaign_group_id = b.lineitem_id and a.UTC_dt between b.start_date and b.end_date;

DROP TABLE IF EXISTS saket.report_geo_cross_dsp;
CREATE TABLE saket.report_geo_cross_dsp
AS
SELECT
  advertiser_id AS dsp_advertiser_id,
  advertiser,
  agency,
  campaign_group_id,
  campaign_id,
  campaign,
  category,
  city_id,
  city_name,
  city_region,
  de_country_name,
  CAST(NULL AS STRING) AS DMA,
  geo_country,
  GEO_DMA,
  geo_region,
  geo_region_name,
  insertion_order_id,
  insertion_order,
  lat,
  lineitem,
  lon,
  pixel_id,
  pixel,
  POSTAL_CODE,
  CAST(NULL AS STRING) AS Postcode,
  CAST(NULL AS STRING) AS State,
  subcategory,
  TO_DATE(UTC_dt) AS UTC_dt,
  SUM(buyer_spend) AS buyer_spend,
  SUM(click) AS clicks,
  SUM(pc_conv+pv_conv) AS conversions,
  dayserial_numeric,
  SUM(imp) AS impressions,
  CAST(NULL AS STRING) AS map_,
  SUM(media_cost_dollars_cpm) AS media_cost_dollars_cpm,
  SUM(pc_conv) AS pc_conversions,
  SUM(pv_conv) AS pv_conversions,
  COALESCE(miq_advertiser_id, -1) AS miq_advertiser_id,
  COALESCE(miq_advertiser_name, 'Unknown') AS miq_advertiser_name,
  agency_id,
  COALESCE(agency_name, 'Unknown') AS agency_name,
  COALESCE(jarvis_campaign_id, -1) AS jarvis_campaign_id,
  COALESCE(dsp, 'Unknown') AS dsp
FROM saket.tableau_geo_report_tmp
GROUP BY
  TO_DATE(UTC_dt),
  geo_country,
  de_country_name,
  advertiser_id,
  advertiser,
  category,
  subcategory,
  agency,
  insertion_order_id,
  insertion_order,
  campaign_group_id,
  lineitem,
  campaign_id,
  campaign,
  pixel_id,
  pixel,
  dayserial_numeric,
  geo_region,
  geo_region_name,
  city_id,
  city_name,
  city_region,
  GEO_DMA,
  POSTAL_CODE,
  lat,
  lon,
  miq_advertiser_id,
  miq_advertiser_name,
  agency_id,
  agency_name,
  jarvis_campaign_id,
  dsp;


DROP TABLE IF EXISTS saket.google_dbm_insights_geo_tmp;
CREATE TABLE saket.google_dbm_insights_geo_tmp
AS
SELECT
  a.utc_date,
  a.dt,
  a.country,
  a.country_name,
  a.timezone,
  a.adv_tz_offset,
  a.advertiser_id,
  a.insertion_order_id,
  CAST(a.line_item_id AS STRING) AS line_item_id,
  a.floodlight_id as pixel_id,
  a.geo_region_id,
  a.region_name,
  a.city_id,
  a.city_name,
  a.dma_code,
  a.postal_code,
  a.lat,
  a.lon,
  a.impressions,
  a.clicks,
  a.conversions,
  a.buyer_spend,
  a.day_numeric,
  b.miq_advertiser_id,
  b.miq_advertiser_name,
  b.agency_id,
  b.agency_name,
  b.campaign_id AS jarvis_campaign_id,
  b.dsp
FROM saket.google_dbm_insights_geo a
LEFT JOIN saket.combined_dsp_lookup b ON a.insertion_order_id = b.insertion_order_id and a.line_item_id = b.placement_id and a.utc_date between b.start_date and b.end_date;

INSERT INTO saket.report_geo_cross_dsp
SELECT
  advertiser_id,
  NULL,
  NULL,
  line_item_id,
  NULL,
  NULL,
  NULL,
  city_id,
  city_name,
  NULL,
  country_name,
  NULL,
  country,
  dma_code,
  geo_region_id,
  region_name,
  insertion_order_id,
  NULL,
  lat,
  NULL,
  lon,
  pixel_id,
  NULL,
  postal_code,
  NULL,
  NULL,
  NULL,
  utc_date,
  SUM(buyer_spend) AS buyer_spend,
  SUM(clicks) AS clicks,
  SUM(conversions) AS conversions,
  day_numeric,
  SUM(impressions) As impressions,
  NULL,
  NULL,
  NULL,
  NULL,
  COALESCE(miq_advertiser_id, -1) AS miq_advertiser_id,
  COALESCE(miq_advertiser_name, 'Unknown') AS miq_advertiser_name,
  agency_id,
  COALESCE(agency_name, 'Unknown') AS agency_name,
  COALESCE(jarvis_campaign_id, -1) AS jarvis_campaign_id,
  COALESCE(dsp, 'Unknown') AS dsp
FROM saket.google_dbm_insights_geo_tmp
GROUP BY
  utc_date,
  country,
  country_name,
  advertiser_id,
  insertion_order_id,
  line_item_id,
  geo_region_id,
  region_name,
  city_id,
  city_name,
  dma_code,
  postal_code,
  lat,
  lon,
  day_numeric,
  pixel_id,
  miq_advertiser_id,
  miq_advertiser_name,
  agency_id,
  agency_name,
  jarvis_campaign_id,
  dsp;
