drop table if exists saket.report_url_keword_wl;
create external table saket.report_url_keword_wl(
  dayserial_numeric         int,
  dt                        date,
  monthname                 string,
  week                      string,
  geo_country               string,
  advertiser_id             int,
  advertiser_name           string,
  insertion_order_id        int,
  insertion_order_name      string,
  lineitem_id               int,
  lineitem_name             string,
  campaign_id               int,
  placement_name            string,
  pixel_id                  int,
  pixel_name                string,
  site_domain_parse         string,
  site_domain               string,
  site_domain_category      string,
  site_domain_subcategory   string,
  word                      string,
  imps                      int,
  clicks                    int,
  pv_convs                  int,
  pc_convs                  int,
  media_cost                double,
  advertiser_category       string,
  advertiser_subcategory    string,
  dsp_filter                string,
  final_wl_bl               string
)
partitioned by (day_numeric string) row format delimited fields terminated by '\t'
stored as textfile
location 's3://dwh-reports-data/srs_reports/daily_adsafe/report_sitedomain_keyword_wl/';

alter table saket.report_url_keword_wl add partition (day_numeric=$DAYSERIAL_NUMERIC$);


drop table if exists saket.report_url_keword_wl_tmp;
create table saket.report_url_keword_wl_tmp
as
select
  a.dayserial_numeric,
  a.dt,
  a.monthname,
  a.week,
  a.geo_country,
  a.advertiser_id,
  a.advertiser_name,
  a.insertion_order_id,
  a.insertion_order_name,
  a.lineitem_id,
  a.lineitem_name,
  a.campaign_id,
  a.placement_name,
  a.pixel_id,
  a.pixel_name,
  a.site_domain_parse,
  a.site_domain,
  a.site_domain_category,
  a.site_domain_subcategory,
  a.word,
  a.imps,
  a.clicks,
  a.pv_convs,
  a.pc_convs,
  a.media_cost,
  a.advertiser_category,
  a.advertiser_subcategory,
  a.dsp_filter,
  a.final_wl_bl,
  b.miq_advertiser_id,
  b.miq_advertiser_name,
  b.agency_id,
  b.agency_name,
  b.campaign_id AS jarvis_campaign_id,
  b.dsp
from saket.report_url_keword_wl a
  left join saket.combined_dsp_lookup b on a.insertion_order_id = b.insertion_order_id;

drop table if exists saket.report_url_keyword_cross_dsp;
create table saket.report_url_keyword_cross_dsp
as
select
  advertiser_category,
  advertiser_id as dsp_advertiser_id,
  advertiser_name,
  advertiser_subcategory,
  CAST(NULL AS STRING) AS campaign_group_id,
  campaign_id,
  dt,
  final_wl_bl,
  geo_country,
  insertion_order_id,
  insertion_order_name,
  lineitem_name,
  pixel_id,
  pixel_name,
  placement_name,
  site_domain,
  site_domain_category,
  site_domain_parse,
  site_domain_subcategory,
  week,
  word,
  sum(clicks) as clicks,
  dayserial_numeric,
  sum(imps) as impressions,
  sum(media_cost) as media_cost,
  sum(pv_convs) as pvconversions,
  sum(pc_convs) as pcconversions,
  monthname,
  lineitem_id,
  dsp_filter,
  miq_advertiser_id,
  COALESCE(miq_advertiser_name, 'Unknown') AS miq_advertiser_name,
  agency_id,
  COALESCE(agency_name, 'Unknown') AS agency_name,
  COALESCE(jarvis_campaign_id, -1) AS jarvis_campaign_id,
  COALESCE(dsp, 'Unknown') AS dsp
from saket.report_url_keword_wl_tmp
group by
  dayserial_numeric,
  dt,
  week,
  geo_country,
  advertiser_id,
  advertiser_name,
  insertion_order_id,
  insertion_order_name,
  lineitem_name,
  campaign_id,
  placement_name,
  pixel_id,
  pixel_name,
  site_domain_parse,
  site_domain,
  site_domain_category,
  site_domain_subcategory,
  word,
  advertiser_category,
  advertiser_subcategory,
  final_wl_bl,
  lineitem_id,
  monthname,
  dsp_filter,
  miq_advertiser_id,
  miq_advertiser_name,
  agency_id,
  agency_name,
  jarvis_campaign_id,
  dsp;


drop table if exists saket.report_dbm_url_keword_wl;
create external table saket.report_dbm_url_keword_wl
(
  dayserial_numeric         int,
  dt                        date,
  monthname                 string,
  week                      string,
  geo_country               string,
  advertiser_id             int,
  advertiser_name           string,
  insertion_order_id        int,
  insertion_order_name      string,
  lineitem_id               int,
  lineitem_name             string,
  campaign_id               int,
  placement_name            string,
  pixel_id                  int,
  pixel_name                string,
  site_domain_parse         string,
  site_domain               string,
  site_domain_category      string,
  site_domain_subcategory   string,
  word                      string,
  imps                      int,
  clicks                    int,
  pv_convs                  int,
  pc_convs                  int,
  media_cost                double,
  advertiser_category       string,
  advertiser_subcategory    string,
  dsp_filter                string,
  final_wl_bl               string
)
partitioned by (day_numeric string) row format delimited fields terminated by '\t'
stored as textfile
location 's3://dwh-reports-data/srs_reports/dbm_reports/report_url_keyword_dbm_wl/';

alter table saket.report_dbm_url_keword_wl add partition (day_numeric=$DAYSERIAL_NUMERIC$);


drop table if exists saket.report_dbm_url_keword_wl_tmp;
create table saket.report_dbm_url_keword_wl_tmp
as
select
  a.dayserial_numeric,
  a.dt,
  a.monthname,
  a.week,
  a.geo_country,
  a.advertiser_id,
  a.advertiser_name,
  a.insertion_order_id,
  a.insertion_order_name,
  a.lineitem_id,
  a.lineitem_name,
  a.campaign_id,
  a.placement_name,
  a.pixel_id,
  a.pixel_name,
  a.site_domain_parse,
  a.site_domain,
  a.site_domain_category,
  a.site_domain_subcategory,
  a.word,
  a.imps,
  a.clicks,
  a.pv_convs,
  a.pc_convs,
  a.media_cost,
  a.advertiser_category,
  a.advertiser_subcategory,
  a.dsp_filter,
  a.final_wl_bl,
  b.miq_advertiser_id,
  b.miq_advertiser_name,
  b.agency_id,
  b.agency_name,
  b.campaign_id AS jarvis_campaign_id,
  b.dsp
from saket.report_dbm_url_keword_wl a
  left join saket.combined_dsp_lookup b on a.insertion_order_id = b.insertion_order_id;


insert into saket.report_url_keyword_cross_dsp
select
  advertiser_category,
  advertiser_id,
  advertiser_name,
  advertiser_subcategory,
  NULL,
  campaign_id,
  dt,
  final_wl_bl,
  geo_country,
  insertion_order_id,
  insertion_order_name,
  lineitem_name,
  pixel_id,
  pixel_name,
  placement_name,
  site_domain,
  site_domain_category,
  site_domain_parse,
  site_domain_subcategory,
  week,
  word,
  sum(clicks) as clicks,
  dayserial_numeric,
  sum(imps) as impressions,
  sum(media_cost) as media_cost,
  sum(pv_convs) as pvconversions,
  sum(pc_convs) as pcconversions,
  monthname,
  lineitem_id,
  dsp_filter,
  miq_advertiser_id,
  COALESCE(miq_advertiser_name, 'Unknown') AS miq_advertiser_name,
  agency_id,
  COALESCE(agency_name, 'Unknown') AS agency_name,
  COALESCE(jarvis_campaign_id, -1) AS jarvis_campaign_id,
  COALESCE(dsp, 'Unknown') AS dsp
from saket.report_dbm_url_keword_wl_tmp
group by
  dayserial_numeric,
  dt,
  week,
  geo_country,
  advertiser_id,
  advertiser_name,
  insertion_order_id,
  insertion_order_name,
  lineitem_name,
  campaign_id,
  placement_name,
  pixel_id,
  pixel_name,
  site_domain_parse,
  site_domain,
  site_domain_category,
  site_domain_subcategory,
  word,
  advertiser_category,
  advertiser_subcategory,
  final_wl_bl,
  monthname,
  lineitem_id,
  dsp_filter,
  miq_advertiser_id,
  miq_advertiser_name,
  agency_id,
  agency_name,
  jarvis_campaign_id,
  dsp;
