SET mapreduce.map.memory.mb = 3584;
SET mapreduce.reduce.memory.mb = 3584;
SET mapreduce.map.java.opts = -Xmx2867m;
SET mapreduce.reduce.java.opts = -Xmx2867m;
SET mapreduce.map.cpu.vcores = 2;
SET mapreduce.reduce.cpu.vcores = 2;

DROP TABLE IF EXISTS saket.report_timelag_tz_tmp;
CREATE TABLE saket.report_timelag_tz_tmp
AS
SELECT
  a.timezone,
  a.utc_dt,
  a.dt,
  a.adv_TZ_OFFSET,
  a.tag_id,
  a.width,
  a.height,
  a.geo_country,
  a.seller_member_id,
  a.sellername,
  a.buyer_member_id,
  a.creative_id,
  a.creative_name,
  a.advertiser_id,
  a.advertiser_name,
  a.campaign_group_id,
  a.lineitemname,
  a.campaign_id,
  a.campaign_name,
  a.pcconversions,
  a.pvconversions,
  a.utc_imp_dt,
  a.imp_dt,
  a.pixel_id,
  a.pixel_name,
  a.imp_type,
  a.publisher_id,
  a.insertion_order_id,
  a.insertion_order_name,
  a.operating_system,
  a.os_name,
  a.os_family,
  a.browser,
  a.browser_name,
  a.LANGUAGE,
  CAST(a.media_cost_dollars_cpm as DOUBLE) AS media_cost_dollars_cpm,
  a.site_domain,
  a.dayserial_numeric,
  a.time_lag_bucket,
  a.category,
  a.subcategory,
  a.leaf_name,
  b.miq_advertiser_id,
  b.miq_advertiser_name,
  b.agency_id,
  b.agency_name,
  b.campaign_id AS jarvis_campaign_id,
  b.dsp
FROM saket.report_timelag_tz a
LEFT JOIN saket.combined_dsp_lookup b ON a.insertion_order_id = b.insertion_order_id and a.campaign_group_id = b.lineitem_id and a.utc_dt between b.start_date and b.end_date;


DROP TABLE IF EXISTS saket.report_timelag_tz_cross_dsp;
CREATE TABLE saket.report_timelag_tz_cross_dsp
AS
SELECT
  advertiser_id AS dsp_advertiser_id,
  advertiser_name,
  browser_name,
  buyer_member_id,
  campaign_group_id,
  campaign_id,
  campaign_name,
  category,
  creative_id,
  creative_name,
  TO_DATE(dt) AS dt,
  geo_country,
  TO_DATE(imp_dt) AS imp_dt,
  insertion_order_id,
  insertion_order_name,
  LANGUAGE,
  leaf_name,
  lineitemname,
  os_family,
  os_name,
  pixel_id,
  pixel_name,
  publisher_id,
  seller_member_id,
  sellername,
  site_domain,
  subcategory,
  tag_id,
  CAST(NULL AS STRING) AS time_lag,
  time_lag_bucket,
  timezone,
  TO_DATE(utc_dt) AS utc_dt,
  TO_DATE(utc_imp_dt) AS utc_imp_dt,
  adv_TZ_OFFSET,
  browser,
  SUM(pcconversions+pvconversions) AS conversions,
  dayserial_numeric,
  height,
  width,
  imp_type,
  SUM(media_cost_dollars_cpm) AS media_cost_dollars_cpm,
  operating_system,
  SUM(pcconversions) AS pcconversions,
  SUM(pvconversions) AS pvconversions,
  COALESCE(miq_advertiser_id, -1) AS miq_advertiser_id,
  COALESCE(miq_advertiser_name, 'Unknown') AS miq_advertiser_name,
  agency_id,
  COALESCE(agency_name, 'Unknown') AS agency_name,
  COALESCE(jarvis_campaign_id, -1) AS jarvis_campaign_id,
  COALESCE(dsp, 'Unknown') AS dsp
FROM saket.report_timelag_tz_tmp
GROUP BY
  timezone,
  TO_DATE(utc_dt),
  TO_DATE(dt),
  adv_TZ_OFFSET,
  tag_id,
  width,
  height,
  geo_country,
  seller_member_id,
  sellername,
  buyer_member_id,
  creative_id,
  creative_name,
  advertiser_id,
  advertiser_name,
  campaign_group_id,
  lineitemname,
  campaign_id,
  campaign_name,
  TO_DATE(utc_imp_dt),
  TO_DATE(imp_dt),
  pixel_id,
  pixel_name,
  imp_type,
  publisher_id,
  insertion_order_id,
  insertion_order_name,
  operating_system,
  os_name,
  os_family,
  browser,
  browser_name,
  LANGUAGE,
  site_domain,
  dayserial_numeric,
  time_lag_bucket,
  category,
  subcategory,
  leaf_name,
  miq_advertiser_id,
  miq_advertiser_name,
  agency_id,
  agency_name,
  jarvis_campaign_id,
  dsp;

DROP TABLE IF EXISTS saket.report_timelag_dbm_tmp;
CREATE TABLE saket.report_timelag_dbm_tmp
AS
SELECT
  a.timezone,
  a.utc_dt,
  a.dt,
  a.adv_TZ_OFFSET,
  a.country,
  a.country_name,
  a.geo_region_id,
  a.region_name,
  a.city_id,
  a.city_name,
  a.os_id,
  a.os_name,
  a.browser_id,
  a.browser_name,
  a.language,
  a.xchange,
  a.xchange_name,
  a.site_domain,
  a.advertiser_id,
  a.advertiser_name,
  a.insertion_order_id,
  a.insertion_order_name,
  a.line_item_id,
  a.line_item_name,
  a.creative_id,
  a.creative_area,
  a.floodlight_id as pixel_id,
  a.floodlight_name as pixel_name,
  a.post_click_conv,
  a.post_view_conv,
  a.imp_utc_dt,
  a.imp_date,
  a.buyer_spend,
  a.time_lag_bucket,
  a.dayserial_numeric,
  a.category,
  a.subcategory,
  b.miq_advertiser_id,
  b.miq_advertiser_name,
  b.agency_id,
  b.agency_name,
  b.campaign_id AS jarvis_campaign_id,
  b.dsp
FROM saket.report_timelag_dbm a
LEFT JOIN saket.combined_dsp_lookup b ON a.insertion_order_id = b.insertion_order_id and a.line_item_id = b.placement_id and a.utc_dt between b.start_date and b.end_date;

INSERT INTO saket.report_timelag_tz_cross_dsp
SELECT
  advertiser_id,
  advertiser_name,
  browser_name,
  NULL,
  line_item_id,
  NULL,
  NULL,
  category,
  creative_id,
  NULL,
  dt,
  country,
  imp_date,
  insertion_order_id,
  insertion_order_name,
  language,
  NULL,
  NULL,
  NULL,
  os_name,
  pixel_id,
  pixel_name,
  NULL,
  NULL,
  NULL,
  site_domain,
  subcategory,
  NULL,
  NULL,
  time_lag_bucket,
  timezone,
  utc_dt,
  imp_utc_dt,
  adv_TZ_OFFSET,
  browser_id,
  SUM(post_click_conv+post_view_conv) AS conversions,
  dayserial_numeric,
  NULL,
  NULL,
  NULL,
  SUM(buyer_spend) AS media_cost_dollars_cpm,
  NULL,
  SUM(post_click_conv) AS pcconversions,
  SUM(post_view_conv) AS pvconversions,
  COALESCE(miq_advertiser_id, -1) AS miq_advertiser_id,
  COALESCE(miq_advertiser_name, 'Unknown') AS miq_advertiser_name,
  agency_id,
  COALESCE(agency_name, 'Unknown') AS agency_name,
  COALESCE(jarvis_campaign_id, -1) AS jarvis_campaign_id,
  COALESCE(dsp, 'Unknown') AS dsp
FROM saket.report_timelag_dbm_tmp
GROUP BY
  timezone,
  utc_dt,
  dt,
  adv_TZ_OFFSET,
  country,
  creative_id,
  advertiser_id,
  advertiser_name,
  line_item_id,
  imp_utc_dt,
  imp_date,
  insertion_order_id,
  insertion_order_name,
  os_name,
  pixel_id,
  pixel_name,
  browser_id,
  browser_name,
  language,
  site_domain,
  dayserial_numeric,
  time_lag_bucket,
  category,
  subcategory,
  miq_advertiser_id,
  miq_advertiser_name,
  agency_id,
  agency_name,
  jarvis_campaign_id,
  dsp;
